### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by cmal** [CodeFalling/blog-admin#10]
你好，请教codefalling一个问题：我喜欢用单个大的org文件来管理所有的博文，将一级标题作为每篇文章的标题。这样的情况想使用blog-admin的话，

我能想到的一种方式是做一个自动拆分org文件的函数，另一种方式是修改blog-admin能够支持单个大的org文件读取。后一种是不是更靠谱一些，能否提供一些修改的建议？感谢！

**Comment by xcodebuild** [comment]
可以看看blog-admin-backend-org-page.el，改写几个函数的实现（其中包括扫描post读取信息的）能够实现（我并不觉得特别简单，但也不算难以实现）。
另外请问你使用单文件是通过什么方式生成站点的？

**Comment by cmal** [comment]
可能我没有表达清楚，我也是用多个org文件生成站点的。由于习惯在大的文件中撰写文章，所以每次都要把写好的东西粘贴出来重新生成，现在是不是还没有支持单文件生成站点的插件？目前我elisp水平还不行，以后慢慢可以尝试实现一下。一种方案是写一个能将org文件拆分成多个org的插件，另一种是将生成站点的插件改成可以解析单个org文件。

**Comment by xcodebuild** [comment]
确实没有见过单文件生成的，因为`org-mode`大文件性能是个坑。

实现起来应该不会特别难，我记得`org-mode`中可以把单独的`headline`下的内容提取到一个`buffer`，然后后面就和多文件`export`是一样的了。或者使用其他语言直接export整个文件然后再从HTML分离每篇文章的信息（因为python/node解析html比较容易），外部语言渲染 `org-mode` 的方法参见 https://codefalling.com/2015/11/13/use-emacs-to-renderer-org-in-command-line/

`elisp`写的站点生成器则参照：https://github.com/kelvinh/org-page

关于`blog-admin`只是一个前端操作实现，**和生成本身没有关系**。（要支持它可能要实现它的扫描文章列表，删除文章等操作）

**Comment by cmal** [comment]
好的 感谢
