### ISSUE TITLE
Wrong type argument: stringp, nil

### ISSUE THREAD

**Issue by Trevoke** [CodeFalling/blog-admin#12]
I installed this and it worked _once_.

This is my configuration:

``` emacs-lisp
#+BEGIN_SRC emacs-lisp
  (use-package org-page
    :config
    (setq op/repository-directory "~/src/projects/trevoke.github.io")
    (setq op/personal-github-link "https://github.com/trevoke")
    (setq op/site-domain "http://blog.trevoke.net/")
    (setq op/site-main-title "Seven Steps")
    (setq op/site-sub-title "Words... words, they're all we have to go on! — Rosencrantz and Guildenstern are dead"))

  (use-package blog-admin
    :config
    (setq blog-admin-backend-path "~/src/projects/trevoke.github.io")
    (setq blog-admin-backend-type 'org-page)
    (setq blog-admin-backend-new-post-in-drafts t)
    (setq blog-admin-backend-new-post-with-same-name-dir t)
    (setq blog-admin-backend-org-page-drafts "_drafts")) ;; directory to save draft

#+END_SRC
```

When I launch emacs and do `M-x blog-admin-start`, it opens the `*Blog*` buffer but I just get the error in the subject. 

`*Messages*` shows `s-trim-right: Wrong type argument: stringp, nil`.

**Comment by xcodebuild** [comment]
Oh maybe I know how to fix it.. Wait please

**Comment by xcodebuild** [comment]
fixed in https://github.com/CodeFalling/blog-admin/commit/3ac6c3715dbeef80c5aabdad66ac8575d1d9046a

But `mepla` would take some time to update

**Comment by Trevoke** [comment]
Fixed, thanks! :)

I wonder if it might be good to display the filename if you can't parse the title?
