### ISSUE TITLE
How to install on Spacemacs?

### ISSUE THREAD

**Issue by DelightRun** [CodeFalling/blog-admin#13]
I'm not quite understand your install instruction of `Spacemacs` in the project's `README`.
So could you please give us a more detailed version of install instruction?

**Comment by xcodebuild** [comment]
If you use a private spacemacs layer, just add `blog-admin` in your `package.le` then add below code into your `private-layer-name/init-blog-admin`.

If you use a standalone `.spacemacs` file, just add `blog-admin` in your `dotspacemacs-additional-packages`, then add below code into `dotspacemacs/user-init ()`

``` lisp
(use-package blog-admin
  :init
  (progn
    ;; your config
    (setq blog-admin-backend-type 'hexo)
    (setq blog-admin-backend-path "~/codefalling.com")
    (setq blog-admin-backend-new-post-in-drafts t)
    (setq blog-admin-backend-new-post-with-same-name-dir t)
    ))
```
