### ISSUE TITLE
Using Nikola

### ISSUE THREAD

**Issue by Balooga** [CodeFalling/blog-admin#27]
Can you provide any guidance or suggestions with the following error?

```
blog-admin-backend-nikola-build-site: Invalid function: blog-admin-backend-nikola--with-venv                            
cd ~/blog && ~/nikola/bin/nikola build: exited abnormally with code 3.
```

**Comment by punchagan** [comment]
Are you able to build your site without using `blog-admin`? Simple running `nikola build` on the terminal.

Can you execute this command and tell me what happens?
`(shell-command "cd ~/blog && ~/nikola/bin/nikola")`

**Comment by Balooga** [comment]
Sorry, i thought "B  ... Build Site" would initialize the blog.  

Entering `nikola init blog` at the command line initializes the blog, and a subsequent "build site" runs without error.

However I now see the following error when I try to "write a new post";

```
ctbl:cp-get-component: Not found ctbl:component attribute...
Symbol's function definition is void: file-attribute-modification-time
```

**Comment by punchagan** [comment]
Looks like the function is pretty new in Emacs. I'll make some changes and push a fix. Thanks for testing this out, and sorry for the issues you are facing!

**Comment by punchagan** [comment]
I pushed a fix for this but GitHub is [having issues](https://status.github.com/messages). The commit will only show up after things are normal.

**Comment by Balooga** [comment]
Thank you.  I pull from melpa anyway, so it takes several hours for changes here to be reflected there.

**Comment by grauschnabel** [comment]
I still have that issue today, is the fix in melpa already?

**Comment by punchagan** [comment]
Yes, it should be available in Melpa. Can you check that you have the latest version of blog-admin installed? https://melpa.org/#/blog-admin

**Comment by grauschnabel** [comment]
I installed it 3 days ago and did the lates updates via list-packages (see below).

How could I help you with further debugging?

```
[martin@martin-arch ~]$ ls ~/.emacs.d/elpa/blog*
/home/martin/.emacs.d/elpa/blog-admin-readme.txt

/home/martin/.emacs.d/elpa/blog-admin-20160530.2350:
blog-admin-autoloads.el   blog-admin-backend.elc       blog-admin-backend-nikola.el    blog-admin-backend-org-page.elc  blog-admin-pkg.el
blog-admin-autoloads.el~  blog-admin-backend-hexo.el   blog-admin-backend-nikola.elc   blog-admin.el
blog-admin-backend.el     blog-admin-backend-hexo.elc  blog-admin-backend-org-page.el  blog-admin.elc
```

**Comment by punchagan** [comment]
Can you tell me the version of Emacs you are using? 

Also, it would help if you `M-x toggle-debug-on-error` and share the full traceback.

**Comment by grauschnabel** [comment]
I found out that there is a 

> Scanning posts...
> (Shell command failed with code 3 and some error output)
> Scanning posts... Done!

before that message.

And there is

> ```
>                 "cd %s && %s status -Pd"
> ```
> 
> in blog-admin-backend-nikola.el, line 81

So I tried it and found out that my nikola does not support the -P flag (Nikola v7.7.8) 

So maybe its that?

**Comment by punchagan** [comment]
Yes, that is [the issue](https://github.com/CodeFalling/blog-admin/issues/29). You will have to wait for the next release or get onto the master branch of Nikola.

**Comment by grauschnabel** [comment]
ok that was easy (on arch linux) - works now

**Comment by punchagan** [comment]
I think this issue is resolved now, and can be closed.  Feel free to re-open/create a new issue, if required.
