### ISSUE TITLE
nikola backend failed to scan files... w/Nikola v.7.7.8

### ISSUE THREAD

**Issue by nyamada** [CodeFalling/blog-admin#29]
I'm not quite sure about what is supposed to happen, but I do know that 

nikola -Pd fails with Nikola v.7.7.8 since -P is not a valid option flag and so scan-posts needs to be changed in the following fashion (perhaps?) -- have no idea what -P used to do...

(defun -scan-posts ()
  "Scan posts of nikola"
  (when (-posts-dir-changed)
    (message "Scanning posts...")
    (let\* ((resize-mini-windows nil) ;; Don't show output in mini-buffer
           (command (format
                     "cd %s && %s status **-d**"
                     blog-admin-backend-path
                     blog-admin-backend-nikola-executable))
           (output-buffer-name "_blog-admin-backend-nikola-output_")
           (output (shell-command command output-buffer-name output-buffer-name))
           draft-paths published-paths)

**Comment by nyamada** [comment]
Never mind ...I didn't get that nikola status accepts a -P flag in github master branch... I had nikola installed via pip install.

**Comment by punchagan** [comment]
Closing this issue. If you have other issues setting it up, feel free to open a new issue.
