### ISSUE TITLE
nikola - posts in the future

### ISSUE THREAD

**Issue by grauschnabel** [CodeFalling/blog-admin#32]
Hi there,

I use the schedule for new posts much, but it seems that future postings are not integrated with blog-admin.  How do you deal with that?

Martin

**Comment by punchagan** [comment]
Interesting! Incidentally, I happen to have implemented that feature in Nikola (but no longer use it).  I wasn't sure anyone would be using it. 

I am not sure if they should be listed as drafts or published posts.  Do you have any ideas?

**Comment by grauschnabel** [comment]
I don't know if you could have more then 2 states: YES, NO, F(uture).  If not I would like to see it as published, this is the way also wordpress does it.  I think the thing is: draft tells me, there is open work with that post.  published tells me there is nothing to do with the post (even if it is not visible on the website right now.)

**Comment by punchagan** [comment]
Fair enough, I was considering implementing having the third state.  I'll share a first cut implementation, if you'd be willing to try it out and suggest improvements.
